/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 4.9 */
/* Wed Oct 16 22:27:39 2024 */

/* parameterized module instance */
Multiplier __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), .DataB( ), 
    .Result( ));
