/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 1.6 */
/* Wed Oct 16 21:23:27 2024 */

/* parameterized module instance */
SinCosI __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), .Sine( ), 
    .Cosine( ));
